### ISSUE TITLE
Access baobab tree

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#1]
Is the `state` variable in the examples a baobab tree? The methods look similar, but I wasn't sure if it was that tree or a wrapper around it.

Also, is it possible to initialize the baobab tree with custom configuration options? Like adding a `verify`?

**Comment by saulshanabrook** [comment]
It looks like you don't access the baobab tree, but [this controller thing](https://github.com/christianalfoni/cerebral-react-baobab/blob/8ad036a9808fdcc986c10b3837f8e5679e2f37b9/index.js#L15) that wraps it.

And it [doesn't look like](https://github.com/christianalfoni/cerebral-react-baobab/blob/8ad036a9808fdcc986c10b3837f8e5679e2f37b9/index.js#L11) it is possible to define custom baobab options

**Comment by christianalfoni** [comment]
Hi @saulshanabrook, 

They are the mutation methods of Cerebral. They look very similar indeed, though there are more of them with Cerebral :-) Let me know if you feel something is missing!

You can not pass options, but I am deploying a new version now that can!

**Comment by christianalfoni** [comment]
There we go, released new version with options :)

**Comment by saulshanabrook** [comment]
I think that might be record issue fixing + bump version time :+1:
