### ISSUE TITLE
Decorator shows as 'Unknown' in React debugger

### ISSUE THREAD

**Issue by dominicglenn** [christianalfoni/cerebral-react-baobab#10]
When rendering a decorated component using the Decorator decorator (commonly aliased as Cerebral in the examples) the rendered component shows up as `Unknown`. It would be good if the name of the wrapped component was used in part of the name of the decorator, so for example, when wrapping a `Todo` component, it would be automatically named `TodoContainer` or something.

![screen shot 2015-08-09 at 13 45 45](https://cloud.githubusercontent.com/assets/917721/9154908/fc40e462-3e9c-11e5-8b95-6b6a3ba3b574.png)

**Comment by christianalfoni** [comment]
This is fixed in new version just released, thanks for the tip! :-)
