### ISSUE TITLE
Use props for getting state in component

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#12]
I am trying to make some components that have different state paths depending on the props passed in.

For example, if I had an `Item` element and it was passed an `index` prop, and my state had a list of items in it, I would love to be able to do something like this:

``` javascript
@Cerebral(state => {
  item: ['items', state.id]
})
class Item extends React.Component {
  ...
}
```

[Doob's DataWatcher](https://github.com/mistadikay/doob#datawatcher) allows a similar feature.

The other option, and what I am doing now, is just to pass the data from a parent into the children. So if I have a List component, it will pass each Item component data about that Item in its props. Instead, I thought maybe I could pass the Item's path (like `['items', '1']`) to each item and have it get it's own data by using the decorator.

**Comment by saulshanabrook** [comment]
I have figured out there is actually a good performance reason for this too (I think).

Right now I have a `System` component that gets passed a system in its props. Then it passing parts of the system to it's sub components. Whenever a part of the system changes, that whole element is rerendered, because some of it's props changed, which is bad performance wise.

If that element instead passed just the path to itself in the data store to its children, then those children could get the parts they needed individually and when any part changes the whole `System` isn't rerendered.

Does that make any sense?

**Comment by saulshanabrook** [comment]
In the mean time, I implemented this myself like so:

``` javascript
import React from 'react'
import {Mixin} from 'cerebral-react-baobab'

// copied from https://github.com/christianalfoni/cerebral-react-baobab/blob/7ffeb7be101335afeb5bcd87fa5ce822df215330/index.js#L163-L184
var Render = function (Component) {
  return function () {
    var state = this.state || {}
    var props = this.props || {}

    var propsToPass = Object.keys(state).reduce(function (props, key) {
      props[key] = state[key]
      return props
    }, {})

    propsToPass = Object.keys(props).reduce(function (propsToPass, key) {
      propsToPass[key] = props[key]
      return propsToPass
    }, propsToPass)

    propsToPass.signals = this.signals
    propsToPass.recorder = this.recorder
    propsToPass.get = this.get

    return React.createElement(Component, propsToPass)
  }
}

export function Cerebral (propsToPaths) {
  propsToPaths = propsToPaths || () => ({})
  return function (Component) {
    return React.createClass({
      displayName: Component.name + 'Container',
      mixins: [Mixin],
      getStatePaths: function () {
        return propsToPaths(this.props)
      },
      render: Render(Component)
    })
  }
}
```

And it can be used like this:

``` javascript
@Cerebral(props => ({
  address: props.systemPath.concat(['address'])
}))
class Query extends Component {
...
```

**Comment by christianalfoni** [comment]
This should work now on the new `cerebral-react` package :)

**Comment by saulshanabrook** [comment]
:smile:

**Comment by saulshanabrook** [comment]
Yep just upgraded and it works great!
