### ISSUE TITLE
Improve shouldComponentUpdate for arrays

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#13]
If I have a component that takes an array, then `shouldComponentUpdate`  will will be `true` if I pass in an array that is different, but has the same value. This is because it uses `==!` which just tests if the arrays are the same, object not if they have the same values.

I think it would make sense to use React's `shallowCompare`, which is used in their PureRenderMixin, like [this](https://github.com/facebook/react/blob/d8998354ee1e00b928d7ce265cfe541f90f3c5b7/src/addons/ReactComponentWithPureRenderMixin.js#L41-L43).

Thoughts?

**Comment by saulshanabrook** [comment]
FYI if anyone else is trying to do this now, if you use the `Mixin` you can `delete Mixin['shouldComponentUpdate']` and then add the `PureRenderMixin` as well

**Comment by saulshanabrook** [comment]
Nevermind, this doesn't help with comparing lists, they are still unequal with the `PureRenderMixin`

**Comment by saulshanabrook** [comment]
OK I am now using lodash's [`isEqual`](https://lodash.com/docs#isEqual) which does a deep compare. I have gotten much better performance with it. My updates were taking 500ms with the shallow compare default, because it had to rerender so many elements. Now the render time is not noticible.

My `shouldComponentUpdate` looks like this now:

``` javascript
import {isEqual} from 'lodash'
...

      shouldComponentUpdate: function (nextProps, nextState) {
        return !isEqual(this.props, nextProps) || !isEqual(this.state, nextState)
      }
```

I know that deep compares do come with a cost, so maybe this is a by use case sort of thing. What do you think?

**Comment by christianalfoni** [comment]
Hi @saulshanabrook,

Actually, when an object inside the array changes it does not change the reference on all the other objects, only the array. So the way to solve this is to pass each object inside the array to a child component, where the list is the parent component. Now each child component will use `shouldComponentUpdate` to do that same shallow equality check and you are good :-)

Did that make sense? Shallow equality is a very very good thing. You will get into more trouble using isEqual, I promise ;-)

**Comment by christianalfoni** [comment]
If you want this behaviour on the child components without hooking onto state, you can still use the Cerebral mixin. It works like the pureRenderMixin by default, but can also extract state from the controller. 

So:

``` js
@Cerebral()
class MyChild extends React.Component {
  render() {
    return (
      <div>
        <div>{this.props.itemFromArray.name}</div>
      </div>
    );
  }
}
```

This will optimize your list and only render the component that actually changed :-)

**Comment by saulshanabrook** [comment]
@christianalfoni I think that makes sense, but I am a little unclear how it pertains to my usecase.

The basic idea is that I have tree of `System` elements basically, in my state. So there is a top level `System` and each `System` can contain children `System`.

Right now I am just showing the top level systems. so I have a `SystemList` component and it maps through it's systems, which are ordered, so they are in an array. So it calls `<System systemPath={systemsPath.concat([index])}/>` for each `System`, where `systemsPath = ['synced', 'live', 'systems']`

Then each System passes this `systemPath` onto some children to render bits of it.

So I am passing this array (like `['synced', 'live', 'systems', 1]`) around a lot and if I don't do a deep compare, it will be different every time, because I am creating a new object every time.

To see it in more context, [the source is here](https://github.com/lucibus/lucibus/blob/f0dd702a7c1c01b200a7b63587f4eec819f7cefc/caido/app/containers/LiveList.jsx#L57)

**Comment by christianalfoni** [comment]
Aha, I see, you are passing in the path which is new every time due to the "concat".

But is there any reason why you can not just pass in the item from the list itself? Every time you do a change the parent list will do a render, but due to each child component in the list uses the mixin only the item that actually changed will do a render.

So:
1. ParentList component gets the list from the controller
2. ParentList renders new ChildComponents passing in each item from the list as a property
3. Each ChildComponent also uses the mixin to force "PureRender"
4. When the list updates the ParentList component will do a new render
5. Going through each item again and preparing child components
6. But only one object inside the array has actually changed, so only one component will actually do a new render

Or am I misunderstanding the structure here maybe? :-)

**Comment by saulshanabrook** [comment]
I don't wanna just pass in the item itself, because the child component also has to be able to edit it. And although each item has a UUID, since the data structure is a tree (recursive) I would have to find the path of the element before updating it. So if I just pass the path into the child element, then it knows where to update itself, so it can send that path when it sends an update signal.

Also, imagine that each ChildComponent calls sub components to render out parts of itself. It calls one component to render its `address` and another for its `level`. So then it can just pass the path to itself to these Level and Address components, and then the whole ChildComponent is not rerendered when its `level` changes, only the `Level` component. Where as, if I passed all the data about itself directly into the `ChildComponent` as a prop, then it would be rerendered.

**Comment by christianalfoni** [comment]
Hehe, this seems quite complex :-) But what about just passing in the UUID and build the path inside the component instead? As I understand it is only the UUID that is dynamic? So change of UUID will now work with pure rendering, and you can still use a path to do changes?

**Comment by saulshanabrook** [comment]
Yeah I was doing that. The only problem is then when I update I have to search the whole tree recursively to find the path for that UUID.

**Comment by saulshanabrook** [comment]
Which is doable, just seems like a waste when I "know" the path before, I just didn't pass it down.

**Comment by christianalfoni** [comment]
Ah, I see, but pass in the index and the uuid. The uuid is there to make sure a new render appears as required, and the index is used to update?

**Comment by christianalfoni** [comment]
But doing lookups in an array is crazy fast, that is not where you will have any problems. I know the feeling... it feels like a waste, but it really is not :-)

I usually put my data in objects, to more easily reference them. Then I use a separate state for the array, just using the keys to reference the data in the object. Then I use immutable-store mapping function or a facet with baobab. This detaches my data from what I want to display in the view layer... really nice. And whenever I do a change to an object, the mapped array will just magically update itself.

But this runs the mapping function on every change of course, but again... only the ones you actually want to display, which is nice.

**Comment by saulshanabrook** [comment]
But the `index` has to be a list, because it is a tree structure. Since it is a tree structure and not just a list of elements, an `index` wouldn't be specific enough.

**Comment by saulshanabrook** [comment]
Yeah I was thinking about changing to only use references, although in this case it still wouldn't help

**Comment by christianalfoni** [comment]
Hm, I think I do not clearly see the use case here. But it is mulitple levels deep where you attach the index "on each level" to build up the path? or something?

**Comment by christianalfoni** [comment]
Going to bed here, but if you have a GIST I am sure I have some more ideas on how you can solve it :-) ... You could also `[...].join(',')` and then `string.split(',)` inside component. The string would be the same each time, you just change the nature of the path. array -> string -> array, where the string format is what is being checked inside `shouldComponentUpdate`

**Comment by saulshanabrook** [comment]
Exactly. That is what the path is doing. The path is just an index for each level. For example, let's say the data looks like this:

``` json
{  
  "name":"hey",
  "children":[  
    {  
      "name":"hi",
      "children":[  
        {  
          "name":"whats up?"
        },
        {  
          "name":"hey there",
          "children":[  
            {  
              "name":"yeah"
            }
          ]
        }
      ]
    }
  ]
}
```

To update the `"yeah"` element, you need to set path `['children", 0, "children", 1, "children", 0]`.

**Comment by saulshanabrook** [comment]
@christianalfoni Yeah I could join the path into a string then split it again. Anyway, my deep equals is working now. If I run into performance issues with it, I can make a string or just have a shallow-ish equals, which just checks array elements as well.

**Comment by christianalfoni** [comment]
Yeah, true. This is a really unique scenario though, needs some manual wiring :-)

btw, The performance issue on deep equal was related to using it generally inside the mixin for all kinds of checks. So an array with complex objects would be a huge problem. But narrowing it down to your arrays here is a really good solution I think.

This scenario does need some manual wiring, thats for sure

**Comment by saulshanabrook** [comment]
Haha yeah... Thank you so much for talking all of this through with me.

**Comment by christianalfoni** [comment]
Happy to do it! Its the use cases that Cerebral needs to solve, so it is really good to get a deep dive into scenarios things are not completely clear how to solve :-)
