### ISSUE TITLE
Require Component Did Mount

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#4]
I see this in all the examples for components:

``` javascript
  componentDidMount() {
    this.props.signals.appMounted();
  }
```

Should that be included in all of our components?

**Comment by saulshanabrook** [comment]
Oh I assume `appMounted` just a signal in the example you are giving. So to access signals in a component, use `this.props.signals.<signal name>`.

**Comment by christianalfoni** [comment]
Exactly :-)
