### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#6]
I have come accross a few areas that are light in documentation. @christianalfoni I would be happy to tackle these tonight if you think it makes sense. 
- [ ]  `props.signals` is how call a signal in a component
- [ ] using `autocommit: false` with [manual commit action](https://github.com/Yomguithereal/baobab/issues/322#issuecomment-127060364) (this requires exposing the `.commit()` method on the baobab tree)
- [ ] the baobab tree is not accessible. you will use the controller instead

**Comment by christianalfoni** [comment]
Yeah, that would be great, heading off to bed here now :-)

About number 2, there was a missing option on the V2 branch. Should not need to do any comitting etc.  Whole answer here #3
