### ISSUE TITLE
Support Facets

### ISSUE THREAD

**Issue by saulshanabrook** [christianalfoni/cerebral-react-baobab#9]
Facets currently don't work, because when `onReset` is called it tries to set the whole tree, and if it contains any facets then it can't set it (as documented in #8).

I like facets and wonder if there is any way to support them.

**Comment by christianalfoni** [comment]
Its because facets are not correctly implemented yet I believe, in its V2 suggestion. When they are set, they should not be part of the tree. If you try it out without Cerebral it does not work either.

So yeah, lets ask author of Baobab what the status is on that.

**Comment by christianalfoni** [comment]
Have an issue on it here: https://github.com/Yomguithereal/baobab/issues/324

**Comment by christianalfoni** [comment]
Okay, latest version has a fix for facets. Try it out :-)

**Comment by saulshanabrook** [comment]
Sweet! Thanks!
